LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

ifndef SS_HIJACK_WRAPPER_FILENAME
  SS_HIJACK_WRAPPER_FILENAME := hijack-wrapper
endif

LOCAL_SRC_FILES:= hijack-wrapper.c
LOCAL_STATIC_LIBRARIES += libc libcutils liblog

LOCAL_MODULE_TAGS := eng
LOCAL_MODULE := $(SS_HIJACK_WRAPPER_FILENAME)

LOCAL_CFLAGS += -DSS_HIJACK_WRAPPER_BINARY=\"$(SS_HIJACK_WRAPPER_BINARY)\"

LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_OUT)/../install-files/$(SS_HIJACK_WRAPPER_PATH)
LOCAL_FORCE_STATIC_EXECUTABLE := true
include $(BUILD_EXECUTABLE)
