#TWRP
TW_INTERNAL_STORAGE_PATH := "/sdcard"
TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_EXTERNAL_STORAGE_PATH := "/sdcard-ext"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard-ext"
TW_DEFAULT_EXTERNAL_STORAGE := true

SPLASH_RECOVERY_KEY := KEY_MENU
SPLASH_CONTINUE_KEY := KEY_SEARCH

BOARD_DEFAULT_VIRT_SYSTEM_SIZE := 640
BOARD_DEFAULT_VIRT_CACHE_SIZE := 300
TW_CUSTOM_BATTERY_CAPACITY_FIELD := charge_counter

HAVE_SELINUX := true

TW_BRIGHTNESS_PATH := /sys/class/backlight/430_540_960_amoled_bl/brightness

