LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

ifndef SS_DELAY_WRAPPER_FILENAME
  SS_DELAY_WRAPPER_FILENAME := delay-wrapper
endif

ifndef SS_DELAY_WRAPPER_SKIP_FILE
  SS_DELAY_WRAPPER_SKIP_FILE := "/.safestrapped"
endif

LOCAL_SRC_FILES:= delay-wrapper.c
LOCAL_STATIC_LIBRARIES += libc libcutils liblog

LOCAL_MODULE_TAGS := eng
LOCAL_MODULE := $(SS_DELAY_WRAPPER_FILENAME)

LOCAL_CFLAGS += -DSS_DELAY_WRAPPER_BINARY=\"$(SS_DELAY_WRAPPER_BINARY)\" -DSS_DELAY_WRAPPER_SKIP_FILE=\"$(SS_DELAY_WRAPPER_SKIP_FILE)\"

LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_OUT)/../install-files/$(SS_DELAY_WRAPPER_PATH)
LOCAL_FORCE_STATIC_EXECUTABLE := true
include $(BUILD_EXECUTABLE)
